const QUOTE_CURRENCY = "BUSD";
const SYMBOL = "BTCBUSD";
const LEVERAGE = 50; // 50x
const FEE_RATE = 3 / 100 / 100; // 0.03%
const TP_SL_RATE = 10 / 100; // 10%
const INITIAL_QUANTITY = 1 / 1000; // 0.001

export {
  QUOTE_CURRENCY,
  SYMBOL,
  LEVERAGE,
  FEE_RATE,
  TP_SL_RATE,
  INITIAL_QUANTITY
};
